/**
 * Assemble full model-year page object from slug, store, and content.
 * Paths: pagePath, canonicalUrl, image paths. inventoryHref via buildInventoryUrl (optional override).
 *
 * For LLM mode, the CLI uses generator.generatePageContent instead of buildPage; the generator
 * produces meta title/description (clamped via meta.ts) and appends a unique CTA (cta-pool.ts).
 */

import { isDemoMode } from "@/lib/config/demo";
import { demoModelPageImagePath } from "@/lib/demo/model-page-assets";
import { slugify } from "./slug";
import {
  buildTrims,
  buildHeroSubhead,
  buildWhyBullets,
  buildContentFaqs,
  type StoreForContent,
} from "./content";
import {
  getWarrantyFaq,
  normalizeBrandWarranty,
  type BrandWarranty,
} from "./warranty-faqs";
import { buildInventoryUrl } from "@/lib/utils/inventory-url";

/** Optional authoritative specs per model (MPG, horsepower, etc.). Only include values you have a source for. */
export interface ModelSpecs {
  mpgCity?: number;
  mpgHighway?: number;
  horsepower?: number;
  torque?: number;
  engine?: string;
  [key: string]: number | string | undefined;
}

export interface ModelSpec {
  displayName: string;
  category: string;
  inventoryModelOverride?: string;
  /** Optional specs for prompt injection; do not invent numbers when absent. */
  specs?: ModelSpecs;
  /**
   * Optional authoritative schema overrides for the renderer.
   * When present, the renderer will use these values for the Car JSON-LD.
   */
  vehicleSchema?: {
    bodyType?: string;
    fuelType?: string;
    driveWheelConfiguration?: string;
    vehicleSeatingCapacity?: number;
  };
}

export interface StoreConfig extends StoreForContent {
  storeKey: string;
  siteUrl: string;
  /** Optional canonical host (e.g. from JSON); falls back to parsing siteUrl when absent */
  domain?: string;
  brand?: string;
  links?: {
    newInventory?: string;
    usedInventory?: string;
    service?: string;
    scheduleService?: string;
    finance?: string;
    trade?: string;
    contact?: string;
    tires?: string;
    specials?: string;
    performance?: string;
  };
}

export interface ModelYearPage {
  pageType: string;
  make: string;
  model: string;
  year: number;
  pagePath: string;
  canonicalUrl: string;
  seo: { title: string; metaDescription: string };
  images: {
    hero: { alt: string; path: string };
    vehicleJellybean: { alt: string; path: string };
  };
  heroSubhead: string;
  whyBullets: [string, string, string];
  trims: {
    intro: string;
    sections: Array<{
      title: string;
      items: Array<{ label: string; note: string }>;
    }>;
  };
  /**
   * Long-form, locally-focused editorial content sections generated by the LLM.
   * Optional and additive to the core hero, bullets, trims, and FAQs.
   */
  contentSections?: Array<{
    /** Stable identifier for analytics / A/B tests; usually a slug of the title + intent. */
    id: string;
    /** Heading for the section (rendered as an H2/H3 in HTML). */
    title: string;
    /** Optional coarse intent tag (e.g. "local_family_commute", "weekend_adventures"). */
    intent?: string;
    /**
     * 2–4 paragraphs of natural, editorial copy with local references.
     * May contain limited basic HTML tags like <p>, <ul>, <li>, <strong>, <em>.
     */
    bodyHtml: string;
  }>;
  faqs: Array<{ q: string; a: string }>;
  links: { inventoryHref: string };
  /**
   * Absolute URLs from the store config (`store.links.*`) used as allowed targets for internal-link
   * injection. Written when the injection pass runs so the JSON documents which destinations apply.
   */
  internalLinkTargetHrefs?: Array<{ type: string; href: string }>;
  tags: string[];
  storeKey: string;
  /**
   * Optional schema overrides passed from ModelSpec into the saved page JSON.
   * Used only by the renderer when building the `Car` JSON-LD block.
   */
  vehicleSchema?: {
    bodyType?: string;
    fuelType?: string;
    driveWheelConfiguration?: string;
    vehicleSeatingCapacity?: number;
  };
  /** Optional 1–2 sentence summary that captures the local SEO pitch for this model/store. */
  localSeoSummary?: string;
}

export interface BuildPageOptions {
  make: string;
  year: number;
  brandSlug: string; // e.g. "toyota" for path /new-toyota/ and /assets/toyota/
}

function joinUrl(base: string, path: string): string {
  const b = base.replace(/\/+$/, "");
  const p = path.replace(/^\/+/, "/");
  return b + p;
}

export function buildPage(
  store: StoreConfig,
  spec: ModelSpec,
  modelIndex: number,
  options: BuildPageOptions
): ModelYearPage {
  const slug = slugify(spec.displayName);
  const city = store.location?.city ?? "Demotown";
  const state = store.location?.state ?? "PA";
  const dealerName = store.dealerName ?? "Dealer";
  const siteUrl = store.siteUrl ?? "";

  const citySlug = city.toLowerCase().replace(/\s+/g, "-");
  const pagePath = `/new-${options.brandSlug}/${options.year}-${options.brandSlug}-${slug}-${citySlug}-${state.toLowerCase()}.htm`;
  const canonicalUrl = joinUrl(siteUrl, pagePath);

  const assetSlug = slug;
  const heroPath = isDemoMode()
    ? demoModelPageImagePath(options.brandSlug, options.year, assetSlug, "hero")
    : `/assets/${options.brandSlug}/${options.year}/${assetSlug}/${options.year}-${options.brandSlug}-${assetSlug}-hero.webp`;
  const jellyPath = isDemoMode()
    ? demoModelPageImagePath(options.brandSlug, options.year, assetSlug, "jellybean")
    : `/assets/${options.brandSlug}/${options.year}/${assetSlug}/${options.year}-${options.brandSlug}-${assetSlug}-jellybean.webp`;

  const make = options.make;
  const title = `${options.year} ${make} ${spec.displayName} in ${city}, ${state} | ${dealerName}`;
  const metaDescription = `Explore the ${options.year} ${make} ${spec.displayName} at ${dealerName} in ${city}, ${state}. Compare trims, read FAQs, and browse current ${spec.displayName} inventory and availability.`;

  const heroSubhead = buildHeroSubhead(
    spec.displayName,
    spec.category,
    modelIndex,
    store
  );
  const whyBullets = buildWhyBullets(spec.category, modelIndex, store);
  const trims = buildTrims(spec.displayName, modelIndex);
  const contentFaqs = buildContentFaqs(spec.displayName, store, modelIndex, {
    make: options.make,
    year: options.year,
  });
  const brandWarranty: BrandWarranty = normalizeBrandWarranty(store.brand);
  const warrantyFaq = getWarrantyFaq(brandWarranty, modelIndex, spec.category);
  const faqs = [...contentFaqs, warrantyFaq];

  const inventoryBase =
    store.links?.newInventory?.replace(/\/+$/, "") ?? "/new-inventory/index.htm";
  const inventoryHref = buildInventoryUrl({
    baseUrl: inventoryBase,
    format: "dealer_com",
    models: [spec.inventoryModelOverride ?? spec.displayName],
  });

  const county = store.location?.county ?? "Demo County";
  const tags = [
    make,
    spec.displayName,
    `${options.year} ${make} ${spec.displayName}`,
    spec.category,
    `${city} PA`,
    county,
  ];

  return {
    pageType: "model-year",
    make: options.make,
    model: spec.displayName,
    year: options.year,
    pagePath,
    canonicalUrl,
    seo: { title, metaDescription },
    images: {
      hero: {
        alt: `${options.year} ${make} ${spec.displayName} in ${city}, ${state}`,
        path: heroPath,
      },
      vehicleJellybean: {
        alt: `${options.year} ${make} ${spec.displayName} jellybean image`,
        path: jellyPath,
      },
    },
    heroSubhead,
    whyBullets,
    trims,
    faqs,
    links: { inventoryHref },
    tags,
    vehicleSchema: spec.vehicleSchema,
    storeKey: store.storeKey,
  };
}
